spring:
  security:
    oauth2:
      client:
        registration:
          my-client-1:
            client-id: myclient
            client-secret: mysecret
            client-name: AuthorizationServer
            provider: myProvider
            scope: resource-server-read
            redirect-uri-template: http://127.0.0.1:8090/login/oauth2/code/callback
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          myProvider:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token
            #resource server uri
            userInfoUri: http://localhost:9090/user
            userNameAttribute: name123
            userAuthorizationUri: http://localhost:8080/oauth/authorize
#logging:
#  level:
#    org.springframework.web: DEBUG